version: '3.8'

services:
  mdm-scrcpy:
    build: .
    container_name: mdm-scrcpy
    network_mode: host
    ports:
      - "8000:8000"
      - "5000:5000"
    environment:
      CERT_NAME: ${DOMAIN_SCRCPY}
      LETSENCRYPT_HOST: ${DOMAIN_SCRCPY}
      VIRTUAL_HOST: ${DOMAIN_SCRCPY}
      VIRTUAL_PORT: "8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -zv localhost 8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/net/tun:/dev/net/tun